'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Domain.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  中 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CenterString() As String
            Get
                Return ResourceManager.GetString("CenterString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  草取り に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Contract_Kusatori() As String
            Get
                Return ResourceManager.GetString("Contract.Kusatori", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  植木手入れ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Contract_Ueki() As String
            Get
                Return ResourceManager.GetString("Contract.Ueki", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  #1900/01/01# に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DeraultDate() As String
            Get
                Return ResourceManager.GetString("DeraultDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  東特 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property EastSpecialString() As String
            Get
                Return ResourceManager.GetString("EastSpecialString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  東 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property EastString() As String
            Get
                Return ResourceManager.GetString("EastString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  区 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property KuString() As String
            Get
                Return ResourceManager.GetString("KuString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  北特 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NorthSpecialString() As String
            Get
                Return ResourceManager.GetString("NorthSpecialString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  北 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NorthString() As String
            Get
                Return ResourceManager.GetString("NorthString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  御廟 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Ossuary() As String
            Get
                Return ResourceManager.GetString("Ossuary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  二特 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SecondSpecialString() As String
            Get
                Return ResourceManager.GetString("SecondSpecialString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  南 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SouthString() As String
            Get
                Return ResourceManager.GetString("SouthString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  - に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StringHalfHyphen() As String
            Get
                Return ResourceManager.GetString("StringHalfHyphen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  西 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WestString() As String
            Get
                Return ResourceManager.GetString("WestString", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
