'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WPF.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  6桁の管理番号を入力 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CustomerIDLengthError() As String
            Get
                Return ResourceManager.GetString("CustomerIDLengthError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  アイテムが選択されていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NothingSelectedItemMessage() As String
            Get
                Return ResourceManager.GetString("NothingSelectedItemMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  半角数字、ハイフンあり（***-****）で入力してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PostalCodeError() As String
            Get
                Return ResourceManager.GetString("PostalCodeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  必須項目です。必ず入力してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StringEmptyMessage() As String
            Get
                Return ResourceManager.GetString("StringEmptyMessage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
