'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Infrastructure.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  清掃契約 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CleaningContract() As String
            Get
                Return ResourceManager.GetString("CleaningContract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  放棄 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DiscardString() As String
            Get
                Return ResourceManager.GetString("DiscardString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  八 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property EightString() As String
            Get
                Return ResourceManager.GetString("EightString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Excel.Application に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ExcelApp() As String
            Get
                Return ResourceManager.GetString("ExcelApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Iroiro に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FILENAME() As String
            Get
                Return ResourceManager.GetString("FILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  五 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FiveString() As String
            Get
                Return ResourceManager.GetString("FiveString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  HGP行書体 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FontName_HGPGyoushotai() As String
            Get
                Return ResourceManager.GetString("FontName_HGPGyoushotai", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ＭＳ Ｐゴシック に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FontName_MSPGothic() As String
            Get
                Return ResourceManager.GetString("FontName_MSPGothic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ＭＳ Ｐ明朝 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FontName_MSPMintyo() As String
            Get
                Return ResourceManager.GetString("FontName_MSPMintyo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  四 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FourString() As String
            Get
                Return ResourceManager.GetString("FourString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  （ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FullwidthClosingParenthesis() As String
            Get
                Return ResourceManager.GetString("FullwidthClosingParenthesis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  府 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property FuString() As String
            Get
                Return ResourceManager.GetString("FuString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Gawa に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Gawa() As String
            Get
                Return ResourceManager.GetString("Gawa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  GraveNumber に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GraveNumber() As String
            Get
                Return ResourceManager.GetString("GraveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  郡 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GunString() As String
            Get
                Return ResourceManager.GetString("GunString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  HG正楷書体-PRO に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property HGRegularRegularScriptPRO() As String
            Get
                Return ResourceManager.GetString("HGRegularRegularScriptPRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  神奈川県 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property KanagawaString() As String
            Get
                Return ResourceManager.GetString("KanagawaString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  県 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property KenString() As String
            Get
                Return ResourceManager.GetString("KenString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  LastSaveDate に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LastSaveDate() As String
            Get
                Return ResourceManager.GetString("LastSaveDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  LesseeName に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LesseeName() As String
            Get
                Return ResourceManager.GetString("LesseeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ./logs/ExceptionLogs.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LogFilePath() As String
            Get
                Return ResourceManager.GetString("LogFilePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ManagementNumber に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ManagementNumber() As String
            Get
                Return ResourceManager.GetString("ManagementNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  九 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NineString() As String
            Get
                Return ResourceManager.GetString("NineString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  一 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property OneString() As String
            Get
                Return ResourceManager.GetString("OneString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  .\files\IroiroFile.xlsx に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SAVEPATH() As String
            Get
                Return ResourceManager.GetString("SAVEPATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  七 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SevenString() As String
            Get
                Return ResourceManager.GetString("SevenString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  市 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ShiString() As String
            Get
                Return ResourceManager.GetString("ShiString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  六 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SixString() As String
            Get
                Return ResourceManager.GetString("SixString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ㎡ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SquareFootageText() As String
            Get
                Return ResourceManager.GetString("SquareFootageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Call_ShunjyuenData に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_Call_ShunjyuenData() As String
            Get
                Return ResourceManager.GetString("StoredProc_Call_ShunjyuenData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DeleteGravePanel に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_DeleteGravePanel() As String
            Get
                Return ResourceManager.GetString("StoredProc_DeleteGravePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  GetAddress に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_GetAddress() As String
            Get
                Return ResourceManager.GetString("StoredProc_GetAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  GetGravePanelList に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_GetGravePanelList() As String
            Get
                Return ResourceManager.GetString("StoredProc_GetGravePanelList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  GetLastSaveDate に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_GetLastSaveDate() As String
            Get
                Return ResourceManager.GetString("StoredProc_GetLastSaveDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  GetPostalcode に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_GetPostalcode() As String
            Get
                Return ResourceManager.GetString("StoredProc_GetPostalcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Reference_GraveNumber に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_Reference_GraveNumber() As String
            Get
                Return ResourceManager.GetString("StoredProc_Reference_GraveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  RegistrationGravePanel に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_RegistrationGravePanel() As String
            Get
                Return ResourceManager.GetString("StoredProc_RegistrationGravePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  UpdateGravePanel に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StoredProc_UpdateGravePanel() As String
            Get
                Return ResourceManager.GetString("StoredProc_UpdateGravePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  - に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StringHalfHyphen() As String
            Get
                Return ResourceManager.GetString("StringHalfHyphen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  十 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TenString() As String
            Get
                Return ResourceManager.GetString("TenString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  三 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ThreeString() As String
            Get
                Return ResourceManager.GetString("ThreeString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  徳島県 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TokushimaString() As String
            Get
                Return ResourceManager.GetString("TokushimaString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  東京都 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ToukyouString() As String
            Get
                Return ResourceManager.GetString("ToukyouString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  二 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TowString() As String
            Get
                Return ResourceManager.GetString("TowString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  % に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WildCard_Percent() As String
            Get
                Return ResourceManager.GetString("WildCard_Percent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  〇 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ZeroString() As String
            Get
                Return ResourceManager.GetString("ZeroString", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
